### PR TITLE
Calistoga update

### LINKED ISSUE #1: Language info needs to be updated because we have more support now.

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello @EbenSorkin !

Here you can find the update of Calistoga. Except for some small modifications for the accents (Hcedilla and the k anchors), nothing to report, everything looks great! 

As in Voltaire, when you have merged, you can add Yvonne's email address.

Here is the QA if you want to take a look:
[Calistoga_QA.zip](https://github.com/SorkinType/Calistoga/files/9828385/Calistoga_QA.zip)

Closes https://github.com/SorkinType/Calistoga/issues/1

Have a good day!

### CODE REVIEW

**Comment by emmamarichal** [comment]
@EbenSorkin Also, you can update the Readme, for the Changelog part. For now, it's still the template:

> 26 May 2021. Version 1.007
> 
> MAJOR Font turned to a variable font.
> SIGNIFICANT Language support improved. Additional symbols added.
> SIGNIFICANT Kerning improved.

But you can update it with the changes you added.

**Comment by EbenSorkin** [comment]
You mean add the stuff about axis & Hcedilla and the k anchors. No?

If so I'll do that.

-e.

**Comment by emmamarichal** [comment]
Oh no sorry, I thought it was the template, I just added the 1.008 in the list (the current version), so all is good :)

**Comment by emmamarichal** [comment]
Hi @EbenSorkin, could you merge this PR please? Thanks! 😊

**Pull request merged**
